### ISSUE TITLE
Node.registry FutureWarning on running tests

### ISSUE THREAD

**Issue by FelixMau** [oemof/oemof-tabular#52]
I've been installing the latest Version of oemof.tabular successfully on a Windows 10 machine and Linux Mint machine.

Running test_constraints.py FutureWarning occours in @jnnr 
- /lib/python3.8/site-packages/oemof/network/network.py:102
 Automatic registration of `Node`s is deprecated in favour of explicitly adding `Node`s to an `EnergySystem` via `EnergySystem.add`. This feature, i.e. the `Node.registry` attribute and functionality pertaining to it, will be removed in future versions.
(Simmilar for Windows 10 machine)
----
Also see attached logs from running tests:
[linux.log](https://github.com/oemof/oemof-tabular/files/9766110/linux.log)
[windows.log](https://github.com/oemof/oemof-tabular/files/9766111/windows.log)

**Comment by MaGering** [comment]
It concerns only [this line](https://github.com/oemof/oemof-tabular/blob/87a5fc1ec1516bd4a88035bee8a48583547ef6af/tests/test_constraints.py#L90).

I tried to exchange it with 
```
cls.energysystem.add(Node)
```
And
 
```
cls.energysystem.add(Solph.Node(...))
```
leads to `AttributeError: module 'oemof.solph' has no attribute 'Node'`.

Although there is the deprecation warning, so far `oemof.solph` is using `Node.registry` on dev instead of `es.add`.
